### ISSUE TITLE
Test notebooks with nbval

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/freud-examples#10]
@mikemhenry volunteered to help us out with testing our notebooks with `nbval` on PR #7. We should try and get that set up to confirm that our notebooks are running correctly. Such testing might also help us catch issues with our Binder environments if we can run the tests on CI with the appropriate environment created, but I'm not familiar enough with `nbval` to know how difficult that might be.

**Comment by mikemhenry** [comment]
Is this repo going to be used as a git submodule for the `freud` repo?

**Comment by vyasr** [comment]
Yes, it's already in there but is undergoing some drastic revisions to bring it up to speed with the 2.0 API. @bdice is finalizing those changes, but it would be good to have some validation that all necessary changes were made. On review I found a few missed cases, but there may be more that both Bradley and I missed. Having systematic tests would be nice for that.

**Comment by mikemhenry** [comment]
So without worrying about CI right now, you should be able to test like this:
```
pip install pytest nbval
# then in the root of freud-examples
python -m pytest -v --nbval --nbval-lax  
```
I had to install a few packages for some examples, but I'm still running into a lot of errors from differences in the API, but this should make it much faster to find them. The `--nbval-lax` option checks to make sure the cells run without an error, without the option the saved output of the cell is compared to the output, which is really cool but runs into issues if you haven't set things up that way.

**Comment by mikemhenry** [comment]
I didn't want to make this a sneaky edit but `python -m pytest -v --nbval --nbval-lax --ignore=archive/ ` is a better command to use if the archive isn't supposed to be tested.

**Comment by mikemhenry** [comment]
After I got all the software packages I needed, this is the fist error I hit:
```
________________________________________________________________________ examples/Benchmarking RDF against MDAnalysis.ipynb::Cell 4 ________________________________________________________________________
Notebook cell execution failed
Cell 4: Cell execution caused an exception

Input:
freud_rdf = freud.density.RDF(bins=nbins, r_max=r_max, r_min=r_min)
for frame in trajectory:
    freud_rdf.compute(system=frame, reset=False)
freud_rdf

Traceback:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-06a99b49dae2> in <module>
      1 freud_rdf = freud.density.RDF(bins=nbins, r_max=r_max, r_min=r_min)
      2 for frame in trajectory:
----> 3     freud_rdf.compute(system=frame, reset=False)
      4 freud_rdf

freud/density.pyx in freud.density.RDF.compute()

freud/locality.pyx in freud.locality._PairCompute._preprocess_arguments()

freud/locality.pyx in freud.locality.NeighborQuery.from_system()

freud/locality.pyx in freud.locality._RawPoints.__cinit__()

TypeError: __cinit__() takes exactly 2 positional arguments (15625 given)
```

**Comment by vyasr** [comment]
@mikemhenry can you update to latest master? You're running into this bug because the notebook is taking advantage of a new feature introduced in one of our most recent PRs, which enables easier interoperability with various frame-like objects like MDAnalysis or GSD frames.

**Comment by bdice** [comment]
@mikemhenry This is a great find -- thanks for testing it out! I'm trying it locally right now.

**Comment by mikemhenry** [comment]
So far since updating to the newest `freud` I've only ran into issues with missing packages.

**Comment by bdice** [comment]
@mikemhenry Let me know if you get it to run all the way through -- I can't run it locally because of some issue with open file limits on my Mac... which is hard to resolve.

**Comment by mikemhenry** [comment]
not with that attitude fam `ulimit -n 4096`

**Comment by bdice** [comment]
@mikemhenry I was having issues getting that to work earlier, seems that I didn't fully understand the "per-session" nature of the limit. Thanks fam 😉

**Comment by mikemhenry** [comment]
Okay this is the first bug I hit:
```
================================================================================================= FAILURES =================================================================================================
_______________________________________________________________ examples/Using Machine Learning for Structural Identification.ipynb::Cell 9 ________________________________________________________________
Notebook cell execution failed
Cell 9: Cell execution caused an exception

Input:
from umap import UMAP
umap = UMAP(random_state=42)

X_reduced = umap.fit_transform(X)

Traceback:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-10-3c8472543e01> in <module>
----> 1 from umap import UMAP
      2 umap = UMAP(random_state=42)
      3 
      4 X_reduced = umap.fit_transform(X)

ImportError: cannot import name 'UMAP' from 'umap' (/Users/mike/miniconda3/envs/freud/lib/python3.7/site-packages/umap/__init__.py)
```

**Comment by mikemhenry** [comment]
Okay real bug this time:
```
______________________________________________________________________________ examples/HOOMD-MC-W6/HOOMD-MC-W6.ipynb::Cell 1 ______________________________________________________________________________
Notebook cell execution failed
Cell 1: Cell execution caused an exception

Input:
hoomd.context.initialize('')
system = hoomd.init.create_lattice(
    hoomd.lattice.sc(a=1), n=10)
mc = hpmc.integrate.sphere(seed=42, d=0.1, a=0.1)
mc.shape_param.set('A', diameter=0.5)

rdf = freud.density.RDF(rmax=4, dr=0.1)

box = freud.box.Box.from_box(system.box)
w6 = freud.order.LocalWlNear(box, 4, 6, 12)

def calc_rdf(timestep):
    hoomd.util.quiet_status()
    snap = system.take_snapshot()
    hoomd.util.unquiet_status()
    rdf.accumulate(box, snap.particles.position)

def calc_W6(timestep):
    hoomd.util.quiet_status()
    snap = system.take_snapshot()
    hoomd.util.unquiet_status()
    w6.compute(snap.particles.position)
    return np.mean(np.real(w6.Wl))

# Equilibrate the system a bit before accumulating the RDF.
hoomd.run(1e4)
hoomd.analyze.callback(calc_rdf, period=100)

logger = hoomd.analyze.log(filename='output.log',
                           quantities=['w6'],
                           period=100,
                           header_prefix='#',
                           overwrite=True)

logger.register_callback('w6', calc_W6)

hoomd.run(1e4)

# Store the computed RDF in a file
np.savetxt('rdf.csv', np.vstack((rdf.R, rdf.RDF)).T,
           delimiter=',', header='r, rdf')

Traceback:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-8b6b54e5e502> in <module>
      5 mc.shape_param.set('A', diameter=0.5)
      6 
----> 7 rdf = freud.density.RDF(rmax=4, dr=0.1)
      8 
      9 box = freud.box.Box.from_box(system.box)

freud/density.pyx in freud.density.RDF.__cinit__()

TypeError: __cinit__() takes at least 2 positional arguments (0 given)
```

**Comment by vyasr** [comment]
ack I hate Cython sometimes. @bdice this is what I was talking about yesterday with respect to not allowing just keyword arguments. Does the compilation option that you found to enable keyword arguments when there's just one argument also fix this problem?

**Comment by mikemhenry** [comment]
Are you talking about this directive:

>`always_allow_keywords` (True / False)
    Avoid the METH_NOARGS and METH_O when constructing functions/methods which take zero or one arguments. Has no effect on special methods and functions with more than one argument. The METH_NOARGS and METH_O signatures provide faster calling conventions but disallow the use of keywords.

 https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives

**Comment by bdice** [comment]
@vyasr This isn't a Cython problem. There were two notebooks that hadn't been updated from the v1.0 syntax, which have now been fixed. The `always_allow_keywords` solved an unrelated problem. If you run freud `master` and freud-examples `master`, the nbval passes all the way through now. Thanks SO much to @mikemhenry for helping with this! I wouldn't have caught those errors otherwise.  👍

I think everything is resolved here now, unless we want to set up some kind of CI for this. The difficult part about CI is that I often write notebooks for freud-examples based on a feature branch of freud. The tests would typically fail until that feature branch is merged (assuming we build freud from source).

**Comment by vyasr** [comment]
I think it's reasonable for us to say that new examples don't get merged until the actual feature is merged. It would allow us to be more systematic about keeping these up-to-date, which I'm definitely in favor of. I'm OK keeping this issue open and dealing with CI later if you want to push on doing it for now, though.

**Comment by mikemhenry** [comment]
With the most recent freud + this repo I'm running into this error
```

================================================================================================= FAILURES =================================================================================================
_________________________________________________________________________________ module_intros/pmft.PMFTXYZ.ipynb::Cell 4 _________________________________________________________________________________
Notebook cell execution failed
Cell 4: Cell execution caused an exception

Input:
shiftvec = [0.82, 0.82, 0]

window = 2**(1/6)/6 # Smaller window for the shifted case

bins = 50

pmft = freud.pmft.PMFTXYZ(x_max=window, y_max=window, z_max=window,
                          bins=50, shiftvec=shiftvec)

# This data is for isotropic particles, so we will just make some unit quaternions
# to use as the orientations
orientations = np.array([[1, 0, 0, 0]] * pos_data.shape[1])

for i in range(10, pos_data.shape[0]):
    box = box_data[i]
    points = pos_data[i]
    pmft.compute(system=(box, points), orientations=orientations, reset=False)

shifted = pmft.pmft

x, y, z = pmft.bin_centers

Traceback:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-31e093ff8424> in <module>
     15     box = box_data[i]
     16     points = pos_data[i]
---> 17     pmft.compute(system=(box, points), orientations=orientations, reset=False)
     18 
     19 shifted = pmft.pmft

~/Projects/freud/freud/pmft.pyx in freud.pmft.PMFTXYZ.compute()

TypeError: compute() takes at least 2 positional arguments (1 given)
```

**Comment by bdice** [comment]
@mikemhenry We had an inconsistency in the PMFTXYZ API that we noticed just before release. Replace the keyword argument “orientations” with “query_orientations” and that will fix it. PRs welcomed, and thanks for the catch.

**Comment by mikemhenry** [comment]
PR is on the way! I was going nuts in trying to find the error until I realized there is a `pmft.PMFTXYZ.ipynb` and `pmft.PMFTXY.ipynb` where the XY uses the right API.
